const productos = [
    { name: "AREPA TIPO OBLEA", image: require('../images/Arepa-De-Maiz-Peto-Tipo-Oblea-500g.jpeg') },
    { name: "AREPA MEDIANA", image: require('../images/Arepa-de-Maíz-Peto-Mediana.jpeg') },
    { name: "AREPA TIPO PINCHO", image: require('../images/arepa-tipo-pincho.jpeg')  },
    { name: "AREPA CON QUESO - CORRIENTE", image:require('../images/arepa-con-queso corrente.jpeg')  },
    { name: "AREPA CON QUESO- ESPECIAL GRANDE", image: require('../images/arepa-conqueso-especial-grande.jpeg') },
    { name: "AREPA CON QUESO- ESPECIAL PEQUEÑA", image: require('../images/arepa-con-queso-especial-pequeña.jpeg') },
    { name: "AREPA CON QUESO MINI X 10", image: require('../images/arepa-con-queso-mini-x10.jpeg') },
    { name: "AREPA CON QUESO CUADRADA", image: require('../images/arepa-con-queso-cuadrada.jpeg') },
    { name: "AREPA DE CHOCLO-CORRIENTE", image: require('../images/arepa-de-choclo-corriente.jpeg') },
    { name: "AREPA DE CHOCLO CON QUESO GRANDE", image: require('../images/arepa-de-choclo-con-queso-grande.jpeg') },
    { name: "AREPA DE CHOCLO CON QUESO PEQUEÑA", image: require('../images/arepa-choclo-con-queso-pequeña.jpeg') },
    { name: "AREPA BOYACENSE X5", image: require('../images/arepa-boyacense-x-5.jpeg') },
    { name: "AREPA BOYACENSE X10", image: require('../images/arepa-boyacense-x-10.jpeg') },
    { name: "AREPA SANTADERANA", image: require('../images/arepa-santanderana.jpeg') },
    { name: "ALMOJABANAS X5", image: require('../images/almojabanas-x-5.jpeg') },
    { name: "ALMOJABANAS X10", image:require('../images/almojabana-x-10.jpeg')},
    { name: "AREPA CON SEMILLA DE QUINUA", image:require('../images/arepa-semilla-quinua.jpeg')  },
    { name: "AREPA CON SEMILLA DE CHIA", image: require('../images/arepa-semilla-chia.jpeg')  },
    { name: "AREPA CON SEMILLA DE AJONJOLI", image: require('../images/arepa-semilla-ajonjoli.jpeg')  },
    { name: "AREPA CON SEMILLA DE LINANZA", image: require('../images/arepa-semilla-linaza.jpeg')  },
    { name: "AREPA CON SEMILLA DE GIRASOL", image: require('../images/arepa-semilla-girasol.jpeg')  },
    { name: "AREPA CHORICERA", image: require('../images/arepa-choricera.jpeg')  },
    { name: "AREPA LONCHERIA", image: require('../images/arepa-loncheria.jpeg')  },
    { name: "AREPA CON MARGARINA Y SAL", image: require('../images/arepa-margarina-sal.jpeg')  },
    { name: "YUCAREPA", image: require('../images/yucarepa.png') },
    { name: "AREPA TIPO ASADERO X 10", image: require('../images/arepa-asadero.jpeg')  },
    { name: "AREPA PARA RELLENAR # 1", image: require('../images/arepa-rellenar-1-2.jpeg')  },
    { name: "AREPA PARA RELLENAR #2", image: require('../images/arepa-rellenar-1-2.jpeg')  },
    { name: "AREPA PARA RELLENAR #3", image: require('../images/arepa-para-rellenar.jpeg')  },
    { name: "PORCION DE AREPAS X 2 UND", image: require('../images/arepa-porcion-x2.jpeg')  },
    { name: "PORCION DE AREPAS X 3 UND", image: require('../images/arepa-porcionx4.jpeg')  },
    { name: "PORCION DE AREPAS X 4 UND", image: require('../images/arepa-porcionx4.jpeg')  },
    { name: "PORCION DE AREPAS X 5 UND", image: require('../images/arepa-porcionx4.jpeg')  },
    { name: "AREPA SUPER OBLEA", image: require('../images/arepa-superoblea.jpeg')  },
    { name: "BLOQUE DE MASA", image: require('../images/masa.jpeg')  },
    { name: "LIBRAS DE MASA", image: require('../images/masa.jpeg')  },
    { name: "MUTE BOYACENSE", image: require('../images/maiz-peto.jpeg') },
    { name: "LIBRA DE MAIZ PETO", image: require('../images/maiz-peto.jpeg')  },
    { name: "ENVUELTO DE MAIZ X 5 UND", image: require('../images/envueltos.jpeg')  },
    { name: "CANASTAS", image: require('../images/canasta.png')  },
  ];
  
  export default productos;
  