const productos = [
    { name: "AREPA TIPO OBLEA", image: require('../images/Arepa-De-Maiz-Peto-Tipo-Oblea-500g-1-300x300.png') },
    { name: "AREPA MEDIANA", image: require('../images/Arepa-de-Maíz-Peto-Mediana-300x300.png') },
    { name: "AREPA TIPO PINCHO", image: require('../images/Arepa-De-Maiz-Peto-Tipo-Pincho-330-Gramos-300x300.png')  },
    { name: "AREPA CON QUESO - CORRIENTE", image:require('../images/Arepa-De-Maiz-Peto-Con-Queso-450g-600x600.png')  },
    { name: "AREPA CON QUESO- ESPECIAL GRANDE", image: '' },
    { name: "AREPA CON QUESO- ESPECIAL PEQUEÑA", image: '' },
    { name: "AREPA CON QUESO MINI X 10", image: '' },
    { name: "AREPA CON QUESO CUADRADA", image: '' },
    { name: "AREPA DE CHOCLO-CORRIENTE", image: '' },
    { name: "AREPA DE CHOCLO CON QUESO GRANDE", image: '' },
    { name: "AREPA DE CHOCLO CON QUESO PEQUEÑA", image: '' },
    { name: "AREPA BOYACENSE X5", image: '' },
    { name: "AREPA BOYACENSE X10", image: '' },
    { name: "AREPA SANTADERANA", image: '' },
    { name: "ALMOJABANAS X5", image: '' },
    { name: "ALMOJABANAS X10", image: '' },
    { name: "AREPA CON SEMILLA DE QUINUA", image: '' },
    { name: "AREPA CON SEMILLA DE CHIA", image: '' },
    { name: "AREPA CON SEMILLA DE AJONJOLI", image: '' },
    { name: "AREPA CON SEMILLA DE LINANZA", image: '' },
    { name: "AREPA CON SEMILLA DE GIRASOL", image: '' },
    { name: "AREPA CHORICERA", image: '' },
    { name: "AREPA LONCHERIA", image: '' },
    { name: "AREPA CON MARGARINA Y SAL", image: '' },
    { name: "YUCAREPA", image: '' },
    { name: "AREPA TIPO ASADERO X 10", image: '' },
    { name: "AREPA PARA RELLENAR # 1", image: '' },
    { name: "AREPA PARA RELLENAR #2", image: '' },
    { name: "AREPA PARA RELLENAR #3", image: '' },
    { name: "PORCION DE AREPAS X 2 UND", image: '' },
    { name: "PORCION DE AREPAS X 3 UND", image: '' },
    { name: "PORCION DE AREPAS X 4 UND", image: '' },
    { name: "PORCION DE AREPAS X 5 UND", image: '' },
    { name: "AREPA SUPER OBLEA", image: '' },
    { name: "LIBRAS DE MASA", image: '' },
    { name: "MUTE BOYACENSE", image: '' },
    { name: "LIBRA DE MAIZ PETO", image: '' },
    { name: "ENVUELTO DE MAIZ X 5 UND", image: '' },
  ];
  
  export default productos;
  