const productos = [
    { name: "AREPA TIPO OBLEA", image: require('../images/Arepa-De-Maiz-Peto-Tipo-Oblea-500g.jpeg') },
    { name: "AREPA MEDIANA", image: require('../images/Arepa-de-Maíz-Peto-Mediana.jpeg') },
    { name: "AREPA TIPO PINCHO", image: require('../images/arepa-tipo-pincho.jpeg')  },
    { name: "AREPA CON QUESO - CORRIENTE", image:require('../images/arepa-con-queso corrente.jpeg')  },
    { name: "AREPA CON QUESO- ESPECIAL GRANDE", image: require('../images/arepa-conqueso-especial-grande.jpeg') },
    { name: "AREPA CON QUESO- ESPECIAL PEQUEÑA", image: require('../images/arepa-con-queso-especial-pequeña.jpeg') },
    { name: "AREPA CON QUESO MINI X 10", image: require('../images/arepa-con-queso-mini-x10.jpeg') },
    { name: "AREPA CON QUESO CUADRADA", image: require('../images/arepa-con-queso-cuadrada.jpeg') },
    { name: "AREPA DE CHOCLO-CORRIENTE", image: require('../images/arepa-de-choclo-corriente.jpeg') },
    { name: "AREPA DE CHOCLO CON QUESO GRANDE", image: require('../images/arepa-de-choclo-con-queso-grande.jpeg') },
    { name: "AREPA DE CHOCLO CON QUESO PEQUEÑA", image: require('../images/arepa-choclo-con-queso-pequeña.jpeg') },
    { name: "AREPA BOYACENSE X5", image: require('../images/arepa-boyacense-x-5.jpeg') },
    { name: "AREPA BOYACENSE X10", image: require('../images/arepa-boyacense-x-10.jpeg') },
    { name: "AREPA SANTANDEREANA", image: require('../images/arepa-santanderana.jpeg') },
    { name: "ALMOJABANAS X5", image: require('../images/almojabanas-x-5.jpeg') },
    { name: "ALMOJABANAS X10", image:require('../images/almojabana-x-10.jpeg')},
    { name: "AREPA CON SEMILLA DE QUINUA", image: '' },
    { name: "AREPA CON SEMILLA DE CHIA", image: '' },
    { name: "AREPA CON SEMILLA DE AJONJOLI", image: '' },
    { name: "AREPA CON SEMILLA DE LINANZA", image: '' },
    { name: "AREPA CON SEMILLA DE GIRASOL", image: '' },
    { name: "AREPA CHORICERA", image: '' },
    { name: "AREPA LONCHERIA", image: '' },
    { name: "AREPA CON MARGARINA Y SAL", image: '' },
    { name: "YUCAREPA", image: '' },
    { name: "AREPA TIPO ASADERO X 10", image: '' },
    { name: "AREPA PARA RELLENAR # 1", image: '' },
    { name: "AREPA PARA RELLENAR #2", image: '' },
    { name: "AREPA PARA RELLENAR #3", image: '' },
    { name: "PORCION DE AREPAS X 2 UND", image: '' },
    { name: "PORCION DE AREPAS X 3 UND", image: '' },
    { name: "PORCION DE AREPAS X 4 UND", image: '' },
    { name: "PORCION DE AREPAS X 5 UND", image: '' },
    { name: "AREPA SUPER OBLEA", image: '' },
    { name: "LIBRAS DE MASA", image: '' },
    { name: "MUTE BOYACENSE", image: '' },
    { name: "LIBRA DE MAIZ PETO", image: '' },
    { name: "ENVUELTO DE MAIZ X 5 UND", image: '' },
  ];
  
  export default productos;
  